name: Trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 
   branches:
      - master 
   inputs:
      PR_NUMBER:
        description: 'Enter Your PR Number'
        required: true
        type: number   
jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch PR data from GitHub API
        run: |
         const PR=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/pawan2-cloud/testRepo/pulls/4)
         echo "$PR"

      # - name: Display PR data
      #   run: |
      #     cat pr_data.json
            
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Check Event Type
  #     run: |
  #       echo "Branch Name: ${{ github.ref }}"
  #   - name: my run
  #     run: |
  #       echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" 
  #       echo "${{ github.event.pull_request.title }}"   
