name: Trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 
   branches:
      - master 
   inputs:
      PR_NUMBER:
        description: 'Enter Your PR Number'
        required: true
        type: number   
permissions: write-all        
jobs:
  Add_Dev_Ephemeral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Add Ephemeral Link Title
        id: ephemeral_text
        uses: actions/github-script@v7
        with:
          result-encoding: string 
          script: | 
            const owner = 'pawan2-cloud';
            const repo = 'testRepo';
            const pull_number= "${{inputs.PR_NUMBER}}"

            const { data: pr } = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner,
              repo,
              pull_number
            }); 

            if(pr.body.includes("Dev Build: N/A")){
              const new_body = pr.body.replace(`Dev Build: N/A`, `Dev Build: <a href='https://tools-iris-pr-${pull_number}.sox-a.us-east-1.kic-dev.shuttercloud.org'>Dev</a>`);
              await github.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner,
              repo,
              pull_number,
              body: new_body
            });
            }

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Display PR data
      #   run: |
      #     cat pr_data.json
            
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Check Event Type
  #     run: |
  #       echo "Branch Name: ${{ github.ref }}"
  #   - name: my run
  #     run: |
  #       echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" 
  #       echo "${{ github.event.pull_request.title }}"   
