name: Trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 
   branches:
      - master 
   inputs:
      PR_NUMBER:
        description: 'Enter Your PR Number'
        required: true
        type: number   
jobs:
  dev_ephemeral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add Ephemeral Link Title
        run: |
          PR= "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER"
          PR_DATA=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR)

          console.dir(PR_DATA,{depth:null});
            
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Check Event Type
  #     run: |
  #       echo "Branch Name: ${{ github.ref }}"
  #   - name: my run
  #     run: |
  #       echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" 
  #       echo "${{ github.event.pull_request.title }}"   
