name: Trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 
   branches:
      - master 
   inputs:
      PR_NUMBER:
        description: 'Enter Your PR Number'
        required: true
        type: number   
jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20  
      - name: Fetch PR data using GitHub Script
        id: fetch_pr
        uses: actions/github-script@v6
        with:
          script: |
            // Define the repository and PR number
            const owner = 'pawan2-cloud';
            const repo = 'testRepo';
            const pull_number= "${{inputs.PR_NUMBER}}"

            // Fetch the current PR details
            const { data: pr } = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner,
              repo,
              pull_number
            });

            // Log the current PR body
            console.log(`Current PR Body: ${pr.body}`);

            // Define the new body content (you can modify this as needed)
            const new_body = `${pr.body}\n\nThis is the updated body of the pull request.`;

            // Update the PR body
            const { data: updatedPr } = await github.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner,
              repo,
              pull_number,
              body: new_body
            });

            // Log the updated PR body
            console.log(`Updated PR Body: ${updatedPr.body}`);

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Display PR data
      #   run: |
      #     cat pr_data.json
            
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Check Event Type
  #     run: |
  #       echo "Branch Name: ${{ github.ref }}"
  #   - name: my run
  #     run: |
  #       echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" 
  #       echo "${{ github.event.pull_request.title }}"   
