name: Trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 
   branches:
      - master 
   inputs:
      PR_NUMBER:
        description: 'Enter Your PR Number'
        required: true
        type: number   
jobs:
  dev_ephemeral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Add Ephemeral Link Title
        uses: actions/github-script@v7
        with:
          result-encoding: string 
          script: |       
            console.dir(context,{depth:null})
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - name: Check Event Type
  #     run: |
  #       echo "Branch Name: ${{ github.ref }}"
  #   - name: my run
  #     run: |
  #       echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" 
  #       echo "${{ github.event.pull_request.title }}"   
