name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:  
jobs:
  dev_ephemeral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Add Ephemeral Link Title
        id: ephemeral_text
        uses: actions/github-script@v7
        with:
          result-encoding: string 
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const pullRequest = response.data;

            // Log PR data for debugging
            console.log('PR Title:', pullRequest.title);
            console.log('PR Body:', pullRequest.body);
            console.log('PR URL:', pullRequest.html_url);
            
