name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:  
jobs:
  Get_PR_Title_Number:
    name: Get PR Title And Number
    runs-on: ubuntu-latest
    # outputs:
    #   PR_NUMBER: ${{ steps.get_data.outputs.PR_NUMBER }}
    #   PR_TITLE: ${{ steps.get_data.outputs.PR_TITLE }}
    steps:
     - uses: actions/github-script@v6
       id: get_pr_data
       with:
          script: |
               
               const response= await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
                const title=response.data[0].title;
                const prNumber=response.data[0].number
                return {title,prNumber}
      - name: Print PR Info
        run: |
          echo "PR Title: ${{ steps.get_pr_data.outputs.title }}"
          echo "PR Number: ${{ steps.get_pr_data.outputs.prNumber }}"
                  
            
